### ISSUE TITLE
Seeder Factory (Model)

### ISSUE THREAD

**Issue by arthara** [ahmademje/KATrips-Backend#6]
Update Model

~Dummy Data

**Comment by faidzafarrifa** [comment]
Create Seeder for =
A1UsersSeeder
A2PasswordResetsSeeder
A3DataUsersSeeder
A4DataKeretasSeeder
A5DataKelasSeeder
A6DataStasiunsSeeder
A7StatusTiketsSeeder
A8KodePembayaransSeeder
A9StatusPembayaransSeeder
A10DataBayisSeeder
A11DataPenumpangsSeeder
A12DataKeretaKelasSeeder
A13DataPemesanansSeeder
A14DataTiketsSeeder
A15DetailPemesanansSeeder
